<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => '75dc40dae5826c0888ed68a59f442162',
  'DATABASE_URL' => 'mysql://root:123@127.0.0.1:3306/libarydb?serverVersion=5.7&charset=utf8mb4',
);
