<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sonata_Admin_Command_List_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sonata.admin.command.list.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sonata.admin.command.list.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sonata:admin:list', [], 'List all admin services available', false, #[\Closure(name: 'sonata.admin.command.list', class: 'Sonata\\AdminBundle\\Command\\ListAdminCommand')] function () use ($container): \Sonata\AdminBundle\Command\ListAdminCommand {
            return ($container->privates['sonata.admin.command.list'] ?? $container->load('getSonata_Admin_Command_ListService'));
        });
    }
}
