<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Form_Twig_CanonicalizeRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.form.twig.canonicalize_runtime' shared service.
     *
     * @return \Sonata\Form\Twig\CanonicalizeRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Twig/CanonicalizeRuntime.php';

        return $container->privates['sonata.form.twig.canonicalize_runtime'] = new \Sonata\Form\Twig\CanonicalizeRuntime(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
