<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Route_PathInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.route.path_info' shared service.
     *
     * @return \Sonata\AdminBundle\Route\PathInfoBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Builder/RouteBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Route/PathInfoBuilder.php';

        return $container->privates['sonata.admin.route.path_info'] = new \Sonata\AdminBundle\Route\PathInfoBuilder(($container->privates['sonata.admin.audit.manager'] ?? $container->load('getSonata_Admin_Audit_ManagerService')));
    }
}
