<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Doctrine_MapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.doctrine.mapper' shared service.
     *
     * @return \Sonata\Doctrine\Mapper\ORM\DoctrineORMMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Mapper/ORM/DoctrineORMMapper.php';

        return $container->privates['sonata.doctrine.mapper'] = new \Sonata\Doctrine\Mapper\ORM\DoctrineORMMapper();
    }
}
