<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Request_FetcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.request.fetcher' shared service.
     *
     * @return \Sonata\AdminBundle\Request\AdminFetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Request/AdminFetcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Request/AdminFetcher.php';

        return $container->privates['sonata.admin.request.fetcher'] = new \Sonata\AdminBundle\Request\AdminFetcher(($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService()));
    }
}
