<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Command_ActivateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.command.activate_user' shared service.
     *
     * @return \Sonata\UserBundle\Command\ActivateUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Command/ActivateUserCommand.php';

        $container->privates['sonata.user.command.activate_user'] = $instance = new \Sonata\UserBundle\Command\ActivateUserCommand(($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')));

        $instance->setName('sonata:user:activate');
        $instance->setDescription('Activate a user');

        return $instance;
    }
}
