<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Command_SetupAclService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.command.setup_acl' shared service.
     *
     * @return \Sonata\AdminBundle\Command\SetupAclCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Command/SetupAclCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Util/AdminAclManipulatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Util/AdminAclManipulator.php';

        $container->privates['sonata.admin.command.setup_acl'] = $instance = new \Sonata\AdminBundle\Command\SetupAclCommand(($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService()), new \Sonata\AdminBundle\Util\AdminAclManipulator('Sonata\\AdminBundle\\Security\\Acl\\Permission\\MaskBuilder'));

        $instance->setName('sonata:admin:setup-acl');
        $instance->setDescription('Install ACL for Admin Classes');

        return $instance;
    }
}
