<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Block_Service_MenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.block.service.menu' shared service.
     *
     * @return \Sonata\BlockBundle\Block\Service\MenuBlockService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/BlockServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/EditableBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/MenuBlockService.php';

        return $container->services['sonata.block.service.menu'] = new \Sonata\BlockBundle\Block\Service\MenuBlockService(($container->privates['twig'] ?? $container->getTwigService()), ($container->privates['knp_menu.menu_provider.chain'] ?? $container->getKnpMenu_MenuProvider_ChainService()), ($container->services['sonata.block.menu.registry'] ?? $container->load('getSonata_Block_Menu_RegistryService')));
    }
}
