<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_HelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.helper' shared service.
     *
     * @return \Sonata\AdminBundle\Admin\AdminHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Admin/AdminHelper.php';

        return $container->privates['sonata.admin.helper'] = new \Sonata\AdminBundle\Admin\AdminHelper(($container->privates['property_accessor'] ?? $container->getPropertyAccessorService()));
    }
}
