<?php

namespace Container2WjQuzy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Command_GenerateObjectAclService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.command.generate_object_acl' shared service.
     *
     * @return \Sonata\AdminBundle\Command\GenerateObjectAclCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Command/QuestionableCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Command/GenerateObjectAclCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Util/ObjectAclManipulatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Util/ObjectAclManipulator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-orm-admin-bundle/src/Util/ObjectAclManipulator.php';

        $container->privates['sonata.admin.command.generate_object_acl'] = $instance = new \Sonata\AdminBundle\Command\GenerateObjectAclCommand(($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService()), ['sonata.admin.manipulator.acl.object.orm' => new \Sonata\DoctrineORMAdminBundle\Util\ObjectAclManipulator(($container->services['doctrine'] ?? $container->getDoctrineService()))]);

        $instance->setName('sonata:admin:generate-object-acl');
        $instance->setDescription('Install ACL for the objects of the Admin Classes.');

        return $instance;
    }
}
