<?php

namespace ContainerNgftVjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sonata_Admin_Command_Explain_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sonata.admin.command.explain.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sonata.admin.command.explain.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sonata:admin:explain', [], 'Explain an admin service', false, #[\Closure(name: 'sonata.admin.command.explain', class: 'Sonata\\AdminBundle\\Command\\ExplainAdminCommand')] function () use ($container): \Sonata\AdminBundle\Command\ExplainAdminCommand {
            return ($container->privates['sonata.admin.command.explain'] ?? $container->load('getSonata_Admin_Command_ExplainService'));
        });
    }
}
