<?php

namespace ContainerNgftVjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sonata_User_Command_CreateUser_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sonata.user.command.create_user.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sonata.user.command.create_user.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sonata:user:create', [], 'Create a user', false, #[\Closure(name: 'sonata.user.command.create_user', class: 'Sonata\\UserBundle\\Command\\CreateUserCommand')] function () use ($container): \Sonata\UserBundle\Command\CreateUserCommand {
            return ($container->privates['sonata.user.command.create_user'] ?? $container->load('getSonata_User_Command_CreateUserService'));
        });
    }
}
