<?php

namespace ContainerNgftVjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Listener_UserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.listener.user' shared service.
     *
     * @return \Sonata\UserBundle\Listener\UserListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Listener/UserListener.php';

        return $container->privates['sonata.user.listener.user'] = new \Sonata\UserBundle\Listener\UserListener(($container->privates['sonata.user.util.canonical_fields_updater'] ?? ($container->privates['sonata.user.util.canonical_fields_updater'] = new \Sonata\UserBundle\Util\CanonicalFieldsUpdater())), ($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')));
    }
}
