<?php

namespace ContainerNgftVjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Form_Type_ResetPasswordRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.form.type.reset_password_request' shared service.
     *
     * @return \Sonata\UserBundle\Form\Type\ResetPasswordRequestFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Form/Type/ResetPasswordRequestFormType.php';

        return $container->privates['sonata.user.form.type.reset_password_request'] = new \Sonata\UserBundle\Form\Type\ResetPasswordRequestFormType();
    }
}
