<?php

namespace ContainerNgftVjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Command_ChangePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.command.change_password' shared service.
     *
     * @return \Sonata\UserBundle\Command\ChangePasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Command/ChangePasswordCommand.php';

        $container->privates['sonata.user.command.change_password'] = $instance = new \Sonata\UserBundle\Command\ChangePasswordCommand(($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')));

        $instance->setName('sonata:user:change-password');
        $instance->setDescription('Change the password of a user');

        return $instance;
    }
}
