<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Twig_Flashmessage_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.twig.flashmessage.manager' shared service.
     *
     * @return \Sonata\Twig\FlashMessage\FlashManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/twig-extensions/src/FlashMessage/FlashManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/twig-extensions/src/Status/StatusClassRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/twig-extensions/src/FlashMessage/FlashManager.php';

        return $container->services['sonata.twig.flashmessage.manager'] = new \Sonata\Twig\FlashMessage\FlashManager(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ['success' => ['success' => [], 'sonata_flash_success' => [], 'sonata_user_success' => [], 'fos_user_success' => []], 'warning' => ['warning' => [], 'sonata_flash_info' => []], 'danger' => ['error' => [], 'sonata_flash_error' => [], 'sonata_user_error' => []]], ['success' => 'success', 'warning' => 'warning', 'danger' => 'danger']);
    }
}
