<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Security_UserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.security.user_provider' shared service.
     *
     * @return \Sonata\UserBundle\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Security/UserProvider.php';

        return $container->privates['sonata.user.security.user_provider'] = new \Sonata\UserBundle\Security\UserProvider(($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')));
    }
}
