<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Form_Type_ResettingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.user.form.type.resetting' shared service.
     *
     * @return \Sonata\UserBundle\Form\Type\ResettingFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Form/Type/ResettingFormType.php';

        return $container->privates['sonata.user.form.type.resetting'] = new \Sonata\UserBundle\Form\Type\ResettingFormType('App\\Entity\\SonataUserUser');
    }
}
