<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Action_LogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.user.action.logout' shared service.
     *
     * @return \Sonata\UserBundle\Action\LogoutAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Action/LogoutAction.php';

        return $container->services['sonata.user.action.logout'] = new \Sonata\UserBundle\Action\LogoutAction();
    }
}
