<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Security_Handler_RoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.security.handler.role' shared service.
     *
     * @return \Sonata\AdminBundle\Security\Handler\RoleSecurityHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Security/Handler/SecurityHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Security/Handler/RoleSecurityHandler.php';

        return $container->privates['sonata.admin.security.handler.role'] = new \Sonata\AdminBundle\Security\Handler\RoleSecurityHandler(($container->privates['security.authorization_checker'] ?? $container->getSecurity_AuthorizationCheckerService()), 'ROLE_SUPER_ADMIN');
    }
}
