<?php

namespace ContainerVCX2pPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Form_Type_DatetimeRangeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.form.type.datetime_range' shared service.
     *
     * @return \Sonata\Form\Type\DateTimeRangeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Type/DateTimeRangeType.php';

        return $container->privates['sonata.form.type.datetime_range'] = new \Sonata\Form\Type\DateTimeRangeType(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
