<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgftVjp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgftVjp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgftVjp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgftVjp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgftVjp\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgftVjp',
    'container.build_id' => '3507ddb3',
    'container.build_time' => 1659353452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgftVjp');
