<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sonata_User_Command_ChangePassword_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sonata.user.command.change_password.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sonata.user.command.change_password.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sonata:user:change-password', [], 'Change the password of a user', false, #[\Closure(name: 'sonata.user.command.change_password', class: 'Sonata\\UserBundle\\Command\\ChangePasswordCommand')] function () use ($container): \Sonata\UserBundle\Command\ChangePasswordCommand {
            return ($container->privates['sonata.user.command.change_password'] ?? $container->load('getSonata_User_Command_ChangePasswordService'));
        });
    }
}
