<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SbqDS7gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SbqDS7g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SbqDS7g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.SbqDS7g.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.SbqDS7g": it references class "App\\Entity\\Book" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'manager' => '?',
        ]);
    }
}
