<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookAdmin_TemplateRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Admin\BookAdmin.template_registry' shared service.
     *
     * @return \Sonata\AdminBundle\Templating\MutableTemplateRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Templating/MutableTemplateRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Templating/MutableTemplateRegistry.php';

        return $container->services['App\\Admin\\BookAdmin.template_registry'] = new \Sonata\AdminBundle\Templating\MutableTemplateRegistry($container->parameters['sonata.admin.configuration.templates']);
    }
}
