<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Action_RetrieveFormFieldElementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.admin.action.retrieve_form_field_element' shared service.
     *
     * @return \Sonata\AdminBundle\Action\RetrieveFormFieldElementAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Action/RetrieveFormFieldElementAction.php';

        return $container->services['sonata.admin.action.retrieve_form_field_element'] = new \Sonata\AdminBundle\Action\RetrieveFormFieldElementAction(($container->privates['twig'] ?? $container->getTwigService()), ($container->privates['sonata.admin.request.fetcher'] ?? $container->load('getSonata_Admin_Request_FetcherService')), ($container->privates['sonata.admin.helper'] ?? $container->load('getSonata_Admin_HelperService')));
    }
}
