<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_User_Action_RequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.user.action.request' shared service.
     *
     * @return \Sonata\UserBundle\Action\RequestAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Action/RequestAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Mailer/Mailer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Util/TokenGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/user-bundle/src/Util/TokenGenerator.php';

        $a = ($container->privates['twig'] ?? $container->getTwigService());
        $b = ($container->services['router'] ?? $container->getRouterService());

        return $container->services['sonata.user.action.request'] = new \Sonata\UserBundle\Action\RequestAction($a, $b, ($container->privates['security.authorization_checker'] ?? $container->getSecurity_AuthorizationCheckerService()), ($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService()), ($container->privates['sonata.admin.global_template_registry'] ?? $container->getSonata_Admin_GlobalTemplateRegistryService()), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->privates['sonata.user.manager.user'] ?? $container->load('getSonata_User_Manager_UserService')), new \Sonata\UserBundle\Mailer\Mailer($b, $a, new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService())), ['sonata@localhost' => 'Sonata Admin'], '@SonataUser/Admin/Security/Resetting/email.html.twig'), new \Sonata\UserBundle\Util\TokenGenerator(), 7200);
    }
}
