<?php

namespace ContainerDTgjpQP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Command_ExplainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sonata.admin.command.explain' shared service.
     *
     * @return \Sonata\AdminBundle\Command\ExplainAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Command/ExplainAdminCommand.php';

        $container->privates['sonata.admin.command.explain'] = $instance = new \Sonata\AdminBundle\Command\ExplainAdminCommand(($container->privates['sonata.admin.pool'] ?? $container->getSonata_Admin_PoolService()));

        $instance->setName('sonata:admin:explain');
        $instance->setDescription('Explain an admin service');

        return $instance;
    }
}
